### ISSUE TITLE
[USER] Create Follow Petition screen

### ISSUE THREAD

**Issue by oskojess** [oskojess/violencias-invisiveis-app#17]
Here we will follow the tasks step by step. 

- [x] Insert main title [#12](https://github.com/oskojess/violencias-invisiveis-app/issues/12)

- [x] Create Card [#13](https://github.com/oskojess/violencias-invisiveis-app/issues/13)

- [x] Insert Card's label  [#14](https://github.com/oskojess/violencias-invisiveis-app/issues/14)

- [x] Insert description and observation labels [#15](https://github.com/oskojess/violencias-invisiveis-app/issues/15)

- [x] Add icons [#16](https://github.com/oskojess/violencias-invisiveis-app/issues/16)

All taks will have reference materials to improve development flux.
