### ISSUE TITLE
[ADMIN] Create Petition and Return Analysis screen

### ISSUE THREAD

**Issue by oskojess** [oskojess/violencias-invisiveis-app#23]
Here we will follow the tasks step by step. 

- [x] Insert main title [#18](https://github.com/oskojess/violencias-invisiveis-app/issues/18)

- [x] Create Card [#19](https://github.com/oskojess/violencias-invisiveis-app/issues/19)

- [ ] Insert Card's label  [#20](https://github.com/oskojess/violencias-invisiveis-app/issues/20)

- [ ] Insert options select and observation labels [#21](https://github.com/oskojess/violencias-invisiveis-app/issues/21)

- [ ] Add icons [#22](https://github.com/oskojess/violencias-invisiveis-app/issues/22)

(Maybe will have more tasks :heart_decoration:)

All taks will have reference materials to improve development flux.  \o/
