### ISSUE TITLE
[USER] Create Tutorial screen 

### ISSUE THREAD

**Issue by oskojess** [oskojess/violencias-invisiveis-app#30]
Here we will follow the tasks step by step. 

- [ ] Create Video Card [#25](https://github.com/oskojess/violencias-invisiveis-app/issues/26)

- [ ] Create  Dialog Card [#27](https://github.com/oskojess/violencias-invisiveis-app/issues/27)

- [ ] Insert Card's description  [#28](https://github.com/oskojess/violencias-invisiveis-app/issues/28)

- [ ] Add icons [#29](https://github.com/oskojess/violencias-invisiveis-app/issues/29)

All taks will have reference materials to improve development flux.
