### ISSUE TITLE
[USER] Create Principal Main Menu screen

### ISSUE THREAD

**Issue by oskojess** [oskojess/violencias-invisiveis-app#35]
Here we will follow the tasks step by step. 

- [x] Insert main title [#31](https://github.com/oskojess/violencias-invisiveis-app/issues/31)

- [x] Create Card [#32](https://github.com/oskojess/violencias-invisiveis-app/issues/32)

- [x] Insert Card's Title (Iniciar, Acompanhar and Tutorial)  [#33](https://github.com/oskojess/violencias-invisiveis-app/issues/33)

- [x] Add buttons (Começar and Ver) and icons [#34](https://github.com/oskojess/violencias-invisiveis-app/issues/34)

All taks will have reference materials to improve development flux.
